// <auto-generated />
using System;
using HydroponicIOT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HydroponicIOT.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260204075609_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HydroponicIOT.Models.ActuatorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ActuatorType")
                        .HasColumnType("int");

                    b.Property<int>("ControlType")
                        .HasColumnType("int");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("ActuatorLogs");
                });

            modelBuilder.Entity("HydroponicIOT.Models.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("HydroponicIOT.Models.Crop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Crops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Leafy green vegetable",
                            IsActive = true,
                            Name = "Lettuce"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Fruit vegetable",
                            IsActive = true,
                            Name = "Tomato"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Berry fruit",
                            IsActive = true,
                            Name = "Strawberry"
                        });
                });

            modelBuilder.Entity("HydroponicIOT.Models.CropStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CropId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("FanOffTime")
                        .HasColumnType("int");

                    b.Property<int>("FanOnTime")
                        .HasColumnType("int");

                    b.Property<double>("MaxHumidity")
                        .HasColumnType("float");

                    b.Property<double>("MaxPh")
                        .HasColumnType("float");

                    b.Property<double>("MaxTds")
                        .HasColumnType("float");

                    b.Property<double>("MaxTemperature")
                        .HasColumnType("float");

                    b.Property<double>("MinHumidity")
                        .HasColumnType("float");

                    b.Property<double>("MinPh")
                        .HasColumnType("float");

                    b.Property<double>("MinTds")
                        .HasColumnType("float");

                    b.Property<double>("MinTemperature")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PumpOffTime")
                        .HasColumnType("int");

                    b.Property<int>("PumpOnTime")
                        .HasColumnType("int");

                    b.Property<int>("StageOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CropId");

                    b.ToTable("CropStages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CropId = 1,
                            Description = "Initial sprouting phase",
                            FanOffTime = 30,
                            FanOnTime = 10,
                            MaxHumidity = 80.0,
                            MaxPh = 6.5,
                            MaxTds = 800.0,
                            MaxTemperature = 24.0,
                            MinHumidity = 60.0,
                            MinPh = 5.5,
                            MinTds = 500.0,
                            MinTemperature = 18.0,
                            Name = "Germination",
                            PumpOffTime = 15,
                            PumpOnTime = 5,
                            StageOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CropId = 1,
                            Description = "Leaf development phase",
                            FanOffTime = 25,
                            FanOnTime = 15,
                            MaxHumidity = 75.0,
                            MaxPh = 6.2000000000000002,
                            MaxTds = 1200.0,
                            MaxTemperature = 25.0,
                            MinHumidity = 65.0,
                            MinPh = 5.7999999999999998,
                            MinTds = 800.0,
                            MinTemperature = 20.0,
                            Name = "Vegetative",
                            PumpOffTime = 20,
                            PumpOnTime = 10,
                            StageOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CropId = 1,
                            Description = "Ready for harvest",
                            FanOffTime = 20,
                            FanOnTime = 10,
                            MaxHumidity = 70.0,
                            MaxPh = 6.5,
                            MaxTds = 900.0,
                            MaxTemperature = 22.0,
                            MinHumidity = 60.0,
                            MinPh = 6.0,
                            MinTds = 600.0,
                            MinTemperature = 18.0,
                            Name = "Harvest",
                            PumpOffTime = 10,
                            PumpOnTime = 5,
                            StageOrder = 3
                        });
                });

            modelBuilder.Entity("HydroponicIOT.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CropId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("datetime2");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CropId");

                    b.HasIndex("UserId");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 4, 7, 56, 9, 332, DateTimeKind.Utc).AddTicks(7591),
                            CropId = 1,
                            Description = "Main hydroponic system for lettuce",
                            IsActive = true,
                            MacAddress = "AA:BB:CC:DD:EE:01",
                            Name = "Hydroponic Unit 1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 4, 7, 56, 9, 332, DateTimeKind.Utc).AddTicks(7836),
                            CropId = 1,
                            Description = "Secondary hydroponic system",
                            IsActive = true,
                            MacAddress = "AA:BB:CC:DD:EE:02",
                            Name = "Hydroponic Unit 2"
                        });
                });

            modelBuilder.Entity("HydroponicIOT.Models.SensorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("AirHumidity")
                        .HasColumnType("float");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<double?>("Ph")
                        .HasColumnType("float");

                    b.Property<double?>("Tds")
                        .HasColumnType("float");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<double?>("WaterTemperature")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("SensorLogs");
                });

            modelBuilder.Entity("HydroponicIOT.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HydroponicIOT.Models.ActuatorLog", b =>
                {
                    b.HasOne("HydroponicIOT.Models.Device", "Device")
                        .WithMany("ActuatorLogs")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("HydroponicIOT.Models.Alert", b =>
                {
                    b.HasOne("HydroponicIOT.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Device");
                });

            modelBuilder.Entity("HydroponicIOT.Models.CropStage", b =>
                {
                    b.HasOne("HydroponicIOT.Models.Crop", "Crop")
                        .WithMany("CropStages")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crop");
                });

            modelBuilder.Entity("HydroponicIOT.Models.Device", b =>
                {
                    b.HasOne("HydroponicIOT.Models.Crop", "Crop")
                        .WithMany("Devices")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HydroponicIOT.Models.User", null)
                        .WithMany("Devices")
                        .HasForeignKey("UserId");

                    b.Navigation("Crop");
                });

            modelBuilder.Entity("HydroponicIOT.Models.SensorLog", b =>
                {
                    b.HasOne("HydroponicIOT.Models.Device", "Device")
                        .WithMany("SensorLogs")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("HydroponicIOT.Models.Crop", b =>
                {
                    b.Navigation("CropStages");

                    b.Navigation("Devices");
                });

            modelBuilder.Entity("HydroponicIOT.Models.Device", b =>
                {
                    b.Navigation("ActuatorLogs");

                    b.Navigation("SensorLogs");
                });

            modelBuilder.Entity("HydroponicIOT.Models.User", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
